version: '3'
services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      MYSQL_USER: user01
      MYSQL_PASSWORD: password01
      MYSQL_HOST: db

  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: user01
      MYSQL_PASSWORD: password01
